### ISSUE TITLE
tiny bugs

### ISSUE THREAD

**Issue by TheCoderCat418** [azh412/CanItBrute#2]
1. If no password is inserted, it will run forever
2. CANNOT Run on Python 2.7.18  {
File "CanItBrute.py", line 19
    print(f"Trying passwords with the length of {length}")
                                                        ^
SyntaxError: invalid syntax
}
That's about it.
Happy Thanksgiving

**Comment by azh412** [comment]
Thanks!
Happy Thanksgiving!

**Comment by TheCoderCat418** [comment]
No problem!
