### ISSUE TITLE
Command line argument does not work. *Update, any password over a length of 4 does not work*

### ISSUE THREAD

**Issue by OctoRocket** [azh412/CanItBrute#4]
Using any command-line argument does not work and stalls the program instead, vv *sus*

**Comment by OctoRocket** [comment]
*Update, any password over a length of 4 does not work*

**Comment by azh412** [comment]
Seems to be working fine on my testing environment. Where have you tested this?

**Comment by OctoRocket** [comment]
on my windows pc, ill try it on manjaro

**Comment by OctoRocket** [comment]
Just to confirm using command line arguments should show the strings being tried right?

**Comment by azh412** [comment]
In the terminal, yes, assuming you run with python[3] CanItBrute.py [args]

**Comment by OctoRocket** [comment]
wait bruh did you forget to add a requirements.txt file 🤦‍♂️

**Comment by azh412** [comment]
Pretty sure I'm using modules included with Python 3, though.

**Comment by OctoRocket** [comment]
hmm then idk what is happening

**Comment by OctoRocket** [comment]
How are you checking for command line arguments?

**Comment by azh412** [comment]
I'm using `argv` from the sys module.
Specifically in this line: `if len(argv) == 2:`
